dist:     trusty  
sudo:     required 

language: c       

os:
    - linux

compiler:
    - gcc

env:
  global:
    - CODECOV_TOKEN='90b6a608-0d2f-4540-8a40-1fc02988468c'

addons:
  apt:
    packages:
      - lcov
      - valgrind
      - cppcheck
      - make
      - cmake

install:
  - sudo apt update
  - sudo apt install cppcheck


script:
  - mkdir build
  - cd build
  - cmake ..
  - make
  - ctest < ../test.txt --output-on-failure
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ctest < ../test.txt ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ./prog -c a.bin 2 < ../test.txt; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then valgrind --tool=memcheck --leak-check=yes ./prog -r a.bin; fi
  - cd ..
  - cppcheck --enable=all --error-exitcode=1 -I project/include ./project/test ./project/src ./project/include/*.h; fi
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
