version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
      
jobs:
  build:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          mkdir build
          cd build
          cmake ..
          make
          cd ..
  make:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          cd build
          make
          cd ..

  check_prog:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          cd build
          time ./prog_lin ../build/test3.txt
          time ./prog_par ../build/test3.txt
          cd ..
  test:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          cd build
          ctest

  valgrind_and_cppcheck:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          cd build
          sudo apt install -y valgrind
          valgrind ctest
          cd..
          cppcheck project/src/* --error-exitcode=1

workflows:
  my-custom-workflow:
    jobs:
      - build
      - make:
          requires:
            - build
      - check_prog:
          requires:
            - build
            - make
      - test:
          requires:
            - build
            - make
            - check_prog
      - valgrind_and_cppcheck:
          requires:
            - build
            - make
            - check_prog
            - test
